import csv

def getKeys(dicts):
    for dict in dicts:
        keys = set()
        for key in dict.keys():
            keys.add(key)
    keys = list(keys)
    keys.sort()
    keyDict = {}
    for key in keys:
        keyDict[key] = key
    return (keys, keyDict)
        
def writeCSV(dict, filename):
    if not isinstance(dict, list):
        dict = [dict]
    keys, keyDict = getKeys(dict)
    csvFile = open(filename, "wb")
    writer = csv.DictWriter(csvFile, fieldnames=keys)
    writer.writerow(keyDict)
    for row in dict:
        writer.writerow(row)
    csvFile.close()

def getLatexString(data):
    string = str(data)
    string = string.replace("_","\\_")
    return string

def writeLatex(dict, filename, keys = None, empty=" "):
    if not isinstance(dict, list):
        dict = [dict]
    if keys == None:
        keys = getKeys(dict)[0]
    
    file = open(filename, "wt")
    file.write("% This file is generated by JariSandbox/ComplexPPI/Source/Utils/TableUtils.py\n")
    file.write("% DO NOT edit manually, as your changes WILL BE OVERWRITTEN!\n")
    
    file.write("\\begin{tabular}{ | c | ")
    for key in keys:
        file.write(" c |")
    file.write( "}\n")
    file.write("\\hline\n")                       
    file.write(empty)
    for key in keys:
        file.write(" & " + getLatexString(key))
    file.write(" \\\\\n")
    file.write("\\hline\n")                     
    for row in dict:
        for key in keys:
            if row.has_key(key):
                file.write(" & " + getLatexString(row[key]))
            else:
                file.write(" & " + empty)
        file.write(" \\\\\n")
    #file.write("1 & 2 & 3 \\\\\n")
    #file.write("4 & 5 & 6 \\\\\n")
    #file.write("7 & 8 & 9 \\\\\n")
    file.write("\\hline\n")
    file.write("\\end{tabular}\n")
    file.close()
    