# A pipeline with hard-coded parameters for calculating the final
# submission file with pre-built examples for the everything.xml (gold standard)
# and the test.xml file with triggers generated by the mixed methods.
#
# Model in the "predefined" (CLASSIFIER_PARAMS) directory is a link to one of the models
# produced on Louhi.

TRAIN_FILE="/usr/share/biotext/GeniaChallenge/xml/everything.xml"
TEST_FILE="/usr/share/biotext/GeniaChallenge/xml/test.xml:/usr/share/biotext/GeniaChallenge/xml/jari-final-test-edges/jari-final-test-edges.examples"
GOLD_TEST_FILE="/usr/share/biotext/GeniaChallenge/xml/test.xml"
CLASSIFIER_PARAMS="predefined:/usr/share/biotext/GeniaChallenge/xml/jari-results/090306-final-edge-model"
PIPELINE="TwoFileAnalysis.py"
OUTDIR="/usr/share/biotext/GeniaChallenge/xml/jari-test-edges"

pushd ~/cvs_checkout/JariSandbox/ComplexPPI/Source
python $PIPELINE -b GeneralEntityTypeRecognizer -x "style:typed" -c SVMMultiClassClassifier -e AveragingMultiClassEvaluator -y $CLASSIFIER_PARAMS -i $TRAIN_FILE -s $TEST_FILE -o $OUTDIR -m $OUTDIR/jari-test-edges-with-merged.xml -p split-Charniak-Lease
python ../../../CommonUtils/InteractionXML/RecalculateIds.py -i $OUTDIR/jari-test-edges-with-merged.xml -o $OUTDIR/jari-test-edges-with-merged-new-ids.xml
python ../../../CommonUtils/InteractionXML/SplitMergedElements.py -i $OUTDIR/jari-test-edges-with-merged-new-ids.xml -o $OUTDIR/jari-test-edges.xml
python Evaluators/EvaluateInteractionXML.py -i $OUTDIR/jari-test-edges.xml -g $GOLD_TEST_FILE
popd
pushd ~/cvs_checkout/GeniaChallenge/unflattening
python prune.py -c -i $OUTDIR/jari-test-edges.xml -o $OUTDIR/pruned.xml
python unflatten.py -i $OUTDIR/pruned.xml -o $OUTDIR/unflattened.xml
python ../formatConversion/gifxmlToGenia.py -i $OUTDIR/unflattened.xml -o $OUTDIR/final
popd
cp nohup.out $OUTDIR/nohup.out
