"""
Classifiers predict the class of an example.

Most of the Classifier classes are wrappers for external, publicly available
classifier implementations. They are used to predict the classes of examples
generated by ExampleBuilders. The correctness of these predictions can then
be measured with Evaluators.
"""